### ISSUE TITLE
Bug: sigproc.Counter time offset is over-adjusted

### ISSUE THREAD

**Issue by cboulay** [iscoe/ezmsg#59]
If I understand TimeAxis `offset` correctly, it provides the time of the first sample in an AxisArray.

Thus, in the following block,

https://github.com/iscoe/ezmsg/blob/43fef1835e6a7fadba65a65e9b6dba83a30d4245/extensions/ezmsg-sigproc/ezmsg/sigproc/synth.py#L130-L140

it should read

`offset_adj = (self.STATE.cur_settings.n_time - 1) / self.STATE.cur_settings.fs`

e.g., if there is only 1 sample then the adjustment should be 0.

**Comment by griffinmilsap** [comment]
I'm 100% on board with your suggestion here, and I've accepted your PR already.  Completely decoupling from wall-clock time is the correct action.  How about we introduce a new setting:

`t_zero: Optional[float] = None`

If none, and dispatch rate is realtime, it uses time.time() to define t_zero and behaves like normal.  If None, and dispatch rate is some float, it defaults to 0.0 and behaves from there onward with behavior C, which I like because offset continues to increase as it should.

**Comment by cboulay** [comment]
Just a reminder to myself that I tackled essentially this same problem recently when I added playback-over-LSL to pyxdf.
https://github.com/xdf-modules/pyxdf/pull/95/commits/923fce2dce00216fcb21ebef68bca00502f79b36

I should refer to that (tested) solution when coming back to this issue.
